/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FiltroNumerosRouteImport } from './routes/filtro-numeros'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as BuscarGruposRouteImport } from './routes/buscar-grupos'
import { Route as AutoRespostaRouteImport } from './routes/auto-resposta'
import { Route as AquecimentoRouteImport } from './routes/aquecimento'
import { Route as AdicionarMembrosRouteImport } from './routes/adicionar-membros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstanciasIdRouteImport } from './routes/instancias.$id'
import { Route as ApiPublicGroupSearchRouteImport } from './routes/api/public/group-search'

const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltroNumerosRoute = FiltroNumerosRouteImport.update({
  id: '/filtro-numeros',
  path: '/filtro-numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarGruposRoute = BuscarGruposRouteImport.update({
  id: '/buscar-grupos',
  path: '/buscar-grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRespostaRoute = AutoRespostaRouteImport.update({
  id: '/auto-resposta',
  path: '/auto-resposta',
  getParentRoute: () => rootRouteImport,
} as any)
const AquecimentoRoute = AquecimentoRouteImport.update({
  id: '/aquecimento',
  path: '/aquecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarMembrosRoute = AdicionarMembrosRouteImport.update({
  id: '/adicionar-membros',
  path: '/adicionar-membros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanciasIdRoute = InstanciasIdRouteImport.update({
  id: '/instancias/$id',
  path: '/instancias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGroupSearchRoute = ApiPublicGroupSearchRouteImport.update({
  id: '/api/public/group-search',
  path: '/api/public/group-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar-membros': typeof AdicionarMembrosRoute
  '/aquecimento': typeof AquecimentoRoute
  '/auto-resposta': typeof AutoRespostaRoute
  '/buscar-grupos': typeof BuscarGruposRoute
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filtro-numeros': typeof FiltroNumerosRoute
  '/historico': typeof HistoricoRoute
  '/leads': typeof LeadsRoute
  '/membros': typeof MembrosRoute
  '/memoria': typeof MemoriaRoute
  '/instancias/$id': typeof InstanciasIdRoute
  '/api/public/group-search': typeof ApiPublicGroupSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar-membros': typeof AdicionarMembrosRoute
  '/aquecimento': typeof AquecimentoRoute
  '/auto-resposta': typeof AutoRespostaRoute
  '/buscar-grupos': typeof BuscarGruposRoute
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filtro-numeros': typeof FiltroNumerosRoute
  '/historico': typeof HistoricoRoute
  '/leads': typeof LeadsRoute
  '/membros': typeof MembrosRoute
  '/memoria': typeof MemoriaRoute
  '/instancias/$id': typeof InstanciasIdRoute
  '/api/public/group-search': typeof ApiPublicGroupSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar-membros': typeof AdicionarMembrosRoute
  '/aquecimento': typeof AquecimentoRoute
  '/auto-resposta': typeof AutoRespostaRoute
  '/buscar-grupos': typeof BuscarGruposRoute
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/filtro-numeros': typeof FiltroNumerosRoute
  '/historico': typeof HistoricoRoute
  '/leads': typeof LeadsRoute
  '/membros': typeof MembrosRoute
  '/memoria': typeof MemoriaRoute
  '/instancias/$id': typeof InstanciasIdRoute
  '/api/public/group-search': typeof ApiPublicGroupSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar-membros'
    | '/aquecimento'
    | '/auto-resposta'
    | '/buscar-grupos'
    | '/campanhas'
    | '/configuracoes'
    | '/filtro-numeros'
    | '/historico'
    | '/leads'
    | '/membros'
    | '/memoria'
    | '/instancias/$id'
    | '/api/public/group-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar-membros'
    | '/aquecimento'
    | '/auto-resposta'
    | '/buscar-grupos'
    | '/campanhas'
    | '/configuracoes'
    | '/filtro-numeros'
    | '/historico'
    | '/leads'
    | '/membros'
    | '/memoria'
    | '/instancias/$id'
    | '/api/public/group-search'
  id:
    | '__root__'
    | '/'
    | '/adicionar-membros'
    | '/aquecimento'
    | '/auto-resposta'
    | '/buscar-grupos'
    | '/campanhas'
    | '/configuracoes'
    | '/filtro-numeros'
    | '/historico'
    | '/leads'
    | '/membros'
    | '/memoria'
    | '/instancias/$id'
    | '/api/public/group-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarMembrosRoute: typeof AdicionarMembrosRoute
  AquecimentoRoute: typeof AquecimentoRoute
  AutoRespostaRoute: typeof AutoRespostaRoute
  BuscarGruposRoute: typeof BuscarGruposRoute
  CampanhasRoute: typeof CampanhasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FiltroNumerosRoute: typeof FiltroNumerosRoute
  HistoricoRoute: typeof HistoricoRoute
  LeadsRoute: typeof LeadsRoute
  MembrosRoute: typeof MembrosRoute
  MemoriaRoute: typeof MemoriaRoute
  InstanciasIdRoute: typeof InstanciasIdRoute
  ApiPublicGroupSearchRoute: typeof ApiPublicGroupSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtro-numeros': {
      id: '/filtro-numeros'
      path: '/filtro-numeros'
      fullPath: '/filtro-numeros'
      preLoaderRoute: typeof FiltroNumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar-grupos': {
      id: '/buscar-grupos'
      path: '/buscar-grupos'
      fullPath: '/buscar-grupos'
      preLoaderRoute: typeof BuscarGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-resposta': {
      id: '/auto-resposta'
      path: '/auto-resposta'
      fullPath: '/auto-resposta'
      preLoaderRoute: typeof AutoRespostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aquecimento': {
      id: '/aquecimento'
      path: '/aquecimento'
      fullPath: '/aquecimento'
      preLoaderRoute: typeof AquecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar-membros': {
      id: '/adicionar-membros'
      path: '/adicionar-membros'
      fullPath: '/adicionar-membros'
      preLoaderRoute: typeof AdicionarMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instancias/$id': {
      id: '/instancias/$id'
      path: '/instancias/$id'
      fullPath: '/instancias/$id'
      preLoaderRoute: typeof InstanciasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/group-search': {
      id: '/api/public/group-search'
      path: '/api/public/group-search'
      fullPath: '/api/public/group-search'
      preLoaderRoute: typeof ApiPublicGroupSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarMembrosRoute: AdicionarMembrosRoute,
  AquecimentoRoute: AquecimentoRoute,
  AutoRespostaRoute: AutoRespostaRoute,
  BuscarGruposRoute: BuscarGruposRoute,
  CampanhasRoute: CampanhasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FiltroNumerosRoute: FiltroNumerosRoute,
  HistoricoRoute: HistoricoRoute,
  LeadsRoute: LeadsRoute,
  MembrosRoute: MembrosRoute,
  MemoriaRoute: MemoriaRoute,
  InstanciasIdRoute: InstanciasIdRoute,
  ApiPublicGroupSearchRoute: ApiPublicGroupSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
